### ISSUE TITLE
match error in literal block

### ISSUE THREAD

**Issue by zsrkmyn** [marshallward/vim-restructuredtext#16]
The current syntax matches the space sequence of the first line in a literal block as the indent sequence, which is unnecessary and can make mistakes.

For example, vim-restructuredtext considers the second line in the block out of the block with the following text:
```rst
::

  this is in the block
 this is still in the block

this is out of the block
```

However, the result generated by `rst2html` shows that the line is actually in the block.

This is what vim-restructuredtext behaves:
![2017-07-27-172125_271x125_scrot](https://user-images.githubusercontent.com/3772171/28663518-2d013474-72f0-11e7-8c4e-400da4a04631.png)

I simply change the pattern to solve the problem:
```viml
syn region  rstLiteralBlock         matchgroup=rstDelimiter
      \ start='::\_s*\n\ze\s' skip='^$' end='^\s\@!'
      \ contains=@NoSpell
```
This code just checks whether there is a space-like char at the beginning of a line. The reason 
why i don't use `start='::\_s*\n\ze\z(\s\)' skip='^$' end='^\z1\@!'` is that I check the following text, and `rst2html` still considers the third is still in the block:
```rst
::

  this is in the block
 this is still in the block
	this is still in the block

this is out of the block
```
Note that the first line starts with a space but the third line starts with a tab.

I am not sure whether  the code has side-effect.

**Comment by marshallward** [comment]
Thanks for pointing this out.  You are right that there's a problem, the example is very clear in [the spec](http://docutils.sourceforge.net/docs/user/rst/quickref.html#literal-blocks).  (The `We start here` example near the bottom.)

Unfortunately, your change will introduce new problems.  It manages to subvert the indentation question by highlighlighting any line that does not go back to the first column.  Take this example:

    1. This is a long point::

         this is in the block
        apparently this is also in the block

       this is out of the block

Your change will incorrectly highlight the final line, even though `rst2html` will not include it in the literal block.  The `\z1` token is used to track the initial starting block of the token, set by `\ze`.

The error here is that `\ze` is set to match the indentation of the first line of the literal block.  Since your second line indentation is smaller, it incorrectly ends the block.

To fix this, we need to set `\ze` a bit more intelligently.  As the spec says, this is set by the indentation of the previous paragraph.  So we need a better way to identify this, and set `\ze` accordingly.

Thanks again for raising this, hopefully the fix is not too hard.

**Comment by zsrkmyn** [comment]
Yes, you're right! That's something really hard to solve. I can't come up with a good solution XD

**Comment by marshallward** [comment]
Mentioning some progress on this (mostly to myself):

This following changes works for a few cases, but also breaks a few others:

    syn region rstLiteralBlock     matchgroup=rstDelimiter
          \ start='^\z(\_s*\).*\zs::' skip='^$' end='^\z1\s\@!'
          \ contains=@NoSpell

Instead of matching the number of spaces before the first literalblock character (`\z(\s\+\)`), it measures the whitespace before the first block, then continues for each line which has at least 1 more space than the original whitespace.

This is more correct if paragraph were only dealing with whitespace, but paragraphs can also be preceded by things like list elements (`-`, `1.`, etc.) which would not be included in the `\z1` in the end match.  Mixed tab-space is probably another problem.

The correct thing to do here is probably to measure the character length of the indentation and replace it with spaces.  But once again, getting match length is quite difficult in vim.  Possibly circumvented by `execute 'syn region .... '` type evaluations, but that's a messy solution.

Leaving this here in case anyone else has better ideas.  I am wondering if there's an easier solution involving nested regions, but I probably won't have time to think about this for a week or so.

**Comment by marshallward** [comment]
This has been solved some time back but was never closed.  Closing now.
