### ISSUE TITLE
Fold regression

### ISSUE THREAD

**Issue by avidseeker** [marshallward/vim-restructuredtext#75]
Possibly a regression. Folding doesn't seem to work. 

Step1:  Open file

test.rst

```rst
================
Document Heading
================

Heading
=======

Sub-heading
-----------

Paragraphs are separated 
by a blank line.
```

Step2: `let rst_folding_enabled=1`

Debugging Info:
- `:set fdm` (shows manual)
- `vim --version` is 9.1

**Comment by marshallward** [comment]
I can't say if the folding is working the way that it should.  But the flag to enable them is `rst_fold_enabled`, not `rst_folding_enabled`.  Can you try `rst_fold_enabled` and see what happens?

**Comment by avidseeker** [comment]
On Thu Nov 14, 2024 at 8:01 AM PST, Marshall Ward wrote:
> The flag to enable them is `rst_fold_enabled`, not `rst_folding_enabled`. Can you try `rst_fold_enabled` and see what happens?

Yes, I used the right flag, but made a mistake when I manually typed it.

**Comment by marshallward** [comment]
OK thanks for that update.  It seems to work for me, but there seem to be some changes between the version of `syntax/rst.vim` here and in the current vim release.  Can I also just check whether you are using the version in this repository?

**Comment by avidseeker** [comment]
I already included that in the debugging info: vim --version is 9.1.

Last commit on this repo is two years ago. Vim 9.1 is released on Jan 2024.

Also make sure you run `vim --clean mwe.rst` and manually set the flag.

**Comment by marshallward** [comment]
Your date arithmetic is impeccable, but the version on the Vim repository is over four years old, so Vim version number may not be the best indicator of syntax file version.

Also, when a user is having an issue but I can't replicate it, then unfortunately I must sometimes ask questions that seem pedantic or repetitive.

However, I am not sure if the syntax file is the issue here.  Folding worked for me in Vim 8.0 (which I must use at work) but not 9.1.  Something may have changed in Vim which is causing the problem.

I will try to look further and see what might be happening.

I don't use folding and I was not the author of this code, so

**Comment by marshallward** [comment]
I need to amend my previous post, since I had `rst_fold_enabled` turned off.  Folding appears to work for me with both Vim 8.0 and 9.1.

If I run with `--clean`, then it does not work.

So my guess is that some issue may have been fixed in either the current syntax file or one of the other support files.

Can you place the following in your `.vim/` directory and tell me what happens?
* `autoload/RstFold.vim`
* `syntax/rst.vim`
* `ftplugin/rst.vim`

**Comment by avidseeker** [comment]
> Your date arithmetic is impeccable

Thank you. I do try to stay on top of these things.

> Vim version number may not be the best indicator.

My mistake. It was bold to assumed Vim isn't lagging behind two years. 

> Can you place the following in your .vim

Yes. Now it works for me. Thanks.

Kindly keep upstream to date to avoid these problems in the future: https://github.com/vim/vim/

Thanks for maintaining the plugin.
